[package]
name = "terminal-magic"
version = "0.1.0"
authors = ["Patrick Amrein <amrein@ubique.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13.6"
toml = "0.5.6"
serde_derive = "1.0.110"
serde = "1.0.110"
mustache = "0.9.0"
prompts = "0.1.0"
async-std = {version = "1.6.0", features = ["attributes"]}
futures = "0.3.5"