[package]
name = "terminal-magic"
version = "0.1.0"
authors = ["Patrick Amrein <amrein@ubique.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.6"
serde_derive = "1.0.111"
serde = "1.0.111"
mustache = "0.9.0"
prompts = "0.1.0"
async-std = {version = "1.6.0", features = ["attributes"]}
futures = "0.3.5"
clap = {version = "2.33.1", features = ["yaml"]}
dirs = "2.0.2"
colored = "1.9"
diff = "0.1.12"
lazy_static = "1.4.0"
shellexpand = "2.0.0"
indexmap = {version= "1.3.2", features = ["serde-1"]}
git2 = "0.13"
regex = "1.3.9"