[plugin_info]
author = "Manfred Mustermann"
version = "1.0"
plugin_type = "zsh"

[placeholders]
_short_string = "test"

[[placeholders.databases]]
shortName = "shortDatabase"
dbPath = "/path/to/my/db"
containerName = "test_container"
port = "5432"


