[plugin_info]
author = "Manfred Mustermann"
version = "1.0"
plugin_type = {Shell = "zsh"}

[placeholders]
databases = [
    {shortName = "adsad", dbPath = "warnWetter", containerName = "echo_balbal", port = "5432"}
]
